(ns hive-qdrant.config-test
  "Contract + property tests for QdrantConfig.

   Golden: defaults alone resolve to a valid config.
   Property: auto-generated totality/roundtrip/mutation via hive-di.testing."
  (:require [clojure.test :refer [deftest is testing]]
            [hive-dsl.result :as r]
            [hive-di.testing :as ditest]
            [hive-qdrant.config :as cfg]))

;; ---- Golden ---------------------------------------------------------------

(deftest golden-defaults-resolve
  (let [result (cfg/resolve-QdrantConfig {} {:env-fn (constantly nil)})]
    (is (r/ok? result) (str "Defaults must resolve cleanly: " (pr-str result)))
    (let [m (:ok result)]
      (is (= "localhost" (:host m)))
      (is (= 6334 (:port m)))
      (is (nil? (:api-key m)))
      (is (false? (:tls? m)))
      (is (= "hive_qdrant_memory" (:collection-name m))))))

(deftest golden-env-wires-through
  (let [env {"QDRANT_HOST"    "qdrant.svc"
             "QDRANT_PORT"    "6335"
             "QDRANT_API_KEY" "secret"
             "QDRANT_TLS"     "true"}
        result (cfg/resolve-QdrantConfig {} {:env-fn #(get env %)})]
    (is (r/ok? result))
    (let [m (:ok result)]
      (is (= "qdrant.svc" (:host m)))
      (is (= 6335 (:port m)))
      (is (= "secret" (:api-key m)))
      (is (true? (:tls? m))))))

(deftest golden-override-wins-over-env
  (let [env    {"QDRANT_HOST" "from-env"}
        result (cfg/resolve-QdrantConfig {:host "from-override"}
                                          {:env-fn #(get env %)})]
    (is (r/ok? result))
    (is (= "from-override" (-> result :ok :host)))))

(deftest golden-blank-override-falls-through-to-default
  (testing "blank override normalizes to nil and falls through to :default
            (hive-di does NOT re-query env when an override is explicitly blank —
            blank overrides shadow env, then yield the typed default)"
    (let [env    {"QDRANT_HOST" "from-env"}
          result (cfg/resolve-QdrantConfig {:host ""}
                                            {:env-fn #(get env %)})]
      (is (r/ok? result))
      (is (= "localhost" (-> result :ok :host))
          "Blank override → default, regardless of env"))))

(deftest golden-port-string-coercion
  (let [result (cfg/resolve-QdrantConfig {:port "9999"}
                                          {:env-fn (constantly nil)})]
    (is (r/ok? result))
    (is (= 9999 (-> result :ok :port)))))

(deftest golden-tls-bool-coercion
  (doseq [[in expected] [["true"  true]
                         ["false" false]
                         ["1"     true]
                         ["0"     false]]]
    (testing (str "QDRANT_TLS=" in)
      (let [result (cfg/resolve-QdrantConfig {}
                                              {:env-fn {"QDRANT_TLS" in}})]
        (is (r/ok? result))
        (is (= expected (-> result :ok :tls?))
            (str "TLS=" in " should coerce to " expected))))))

;; ---- Property (auto-generated by hive-di) ---------------------------------
;;
;; Requires: org.clojure/test.check, clojure.test.check.clojure-test.
;; Generates:
;;   QdrantConfig-totality       — resolver never throws for any input
;;   QdrantConfig-defaults-only  — defaults alone produce valid config
;;   QdrantConfig-roundtrip      — resolved config survives EDN round-trip
;;   QdrantConfig-field-mutations — removing each default is graceful

(ditest/defconfig-tests QdrantConfig cfg/QdrantConfig-fields
  :num-tests 50)
